/**
 * Jira Comment Draft Emitter
 *
 * Produces a human-readable Jira comment draft from a ReadinessResult.
 * The draft is NEVER posted autonomously — it is returned to the caller
 * along with a `confirm_post_url` gate. Writing to Jira requires explicit
 * human confirmation.
 *
 * Every draft embeds the run_id so the originating analysis is traceable
 * in the evidence store.
 */

import type { ReadinessResult, CommentDraft } from "../types/index.js";

// ---------------------------------------------------------------------------
// Emitter
// ---------------------------------------------------------------------------

export interface DraftEmitterOptions {
  /**
   * Base URL used to construct the confirm_post_url.
   * E.g. "https://product-overlord.internal"
   */
  baseUrl?: string;
}

/**
 * Build a formatted Jira comment draft (Jira wiki-markup / plain text).
 * Embeds run_id, verdict, score, missing items, and clarification questions.
 * Returns a CommentDraft — caller must present this to the user and gate on
 * explicit confirmation before any Jira write.
 */
export function emitCommentDraft(
  result: ReadinessResult,
  run_id: string,
  opts: DraftEmitterOptions = {}
): CommentDraft {
  const baseUrl = opts.baseUrl ?? "https://product-overlord.internal";
  const confirm_post_url = `${baseUrl}/confirm-post/${run_id}/${result.ticket_key}`;

  // Shadow mode: confirm URL is replaced with a no-op to make the gate explicit
  const shadowMode = process.env["SHADOW_MODE"] === "true";
  const effectiveConfirmUrl = shadowMode
    ? `${baseUrl}/shadow-mode-no-op/${run_id}`
    : confirm_post_url;

  if (shadowMode) {
    // Import inline to avoid circular dep — logger is a simple util
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    process.stdout.write(
      JSON.stringify({ level: "info", message: "shadow_mode_draft", context: { run_id, ticket_key: result.ticket_key }, timestamp: new Date().toISOString() }) + "\n"
    );
  }

  const lines: string[] = [];

  // ── Header ────────────────────────────────────────────────────────────────
  lines.push(`h3. Readiness Analysis — ${result.ticket_key}`);
  lines.push("");

  // ── Verdict badge ─────────────────────────────────────────────────────────
  const verdictIcon =
    result.readiness_status === "ready"
      ? "✅"
      : result.readiness_status === "blocked"
      ? "🚫"
      : "⚠️";

  lines.push(
    `*Verdict:* ${verdictIcon} ${result.readiness_status.toUpperCase().replace("_", " ")}  ` +
      `| *Score:* ${result.readiness_score}/100  ` +
      `| *Confidence:* ${Math.round(result.confidence * 100)}%`
  );
  lines.push("");

  // ── Explanation ───────────────────────────────────────────────────────────
  lines.push(`_${result.explanation}_`);
  lines.push("");

  // ── Missing items ─────────────────────────────────────────────────────────
  if (result.missing_items.length > 0) {
    lines.push("*Missing / incomplete:*");
    for (const item of result.missing_items) {
      const icon = item.severity === "high" ? "🔴" : item.severity === "medium" ? "🟡" : "🟢";
      lines.push(`* ${icon} *${item.dimension}* (${item.severity}) — ${item.reason}`);
    }
    lines.push("");
  }

  // ── Questions for PM ──────────────────────────────────────────────────────
  if (result.questions_for_pm.length > 0) {
    lines.push("*Questions for PM:*");
    for (const q of result.questions_for_pm) {
      lines.push(`# ${q}`);
    }
    lines.push("");
  }

  // ── Questions for Engineer ────────────────────────────────────────────────
  if (result.questions_for_engineer.length > 0) {
    lines.push("*Questions for Engineer:*");
    for (const q of result.questions_for_engineer) {
      lines.push(`# ${q}`);
    }
    lines.push("");
  }

  // ── Questions for QA ─────────────────────────────────────────────────────
  if (result.questions_for_qa.length > 0) {
    lines.push("*Questions for QA:*");
    for (const q of result.questions_for_qa) {
      lines.push(`# ${q}`);
    }
    lines.push("");
  }

  // ── Manual checks ─────────────────────────────────────────────────────────
  if (result.manual_checks.length > 0) {
    lines.push("*Manual checks required:*");
    for (const check of result.manual_checks) {
      lines.push(`* ${check}`);
    }
    lines.push("");
  }

  // ── Audit footer ──────────────────────────────────────────────────────────
  lines.push("----");
  lines.push(
    `_Generated by product-overlord · run_id: \`${run_id}\` · This comment requires human approval before posting._`
  );

  return {
    run_id,
    ticket_key: result.ticket_key,
    body: lines.join("\n"),
    confirm_post_url: effectiveConfirmUrl,
  };
}
